### ISSUE TITLE
Project structure adjustment

### ISSUE THREAD

**Issue by luxiaba** [v2ex/remote#16]
The `app.py` will become bigger if there are other functions to be added in the future, if so it'll become hard to read and maintain later.

Have you think about adjusting the structure? for example create some utils/exceptions/init/... and put them into a package to let main code separate from the configuration file and keep the structure of the main project simple and clear.

Or you're prefer the structure of one function one file? for now, image processing is a file, and there may be another file like `weather.py` for weather inquiry in the future?

**Comment by livid** [comment]
I think we can split them into blueprints:

https://flask.palletsprojects.com/en/2.0.x/blueprints/

Each top-level folder turns into a bp.

For example:

- images.py
- network.py (currently for IPIP and DNS resolve)

If multiple blueprints share a function, we can put it in a shared package like utilities. Or a function is specific, like those image functions, they can reside in images.py.

**Comment by luxiaba** [comment]
Sounds great ☺️
