### ISSUE TITLE
Use Github Action to build image and test

### ISSUE THREAD

**Issue by luxiaba** [v2ex/remote#19]
- Build an image with Dockerfile
- Run a container with the image
- Run tests against the container

**Comment by livid** [comment]
Awesome, now I will adjust the script to launch the container on the production.

**Comment by luxiaba** [comment]
Exciting, but maybe the release on prod can wait until tomorrow? I'm want to test it at night to prevent online crashing like last time.

**Comment by livid** [comment]
Yes, I am currently testing it in staging. Since there is no significant feature change, it can wait.

We probably need an extra step after:

```
name: Build And Push
```

We need to test that just built image can at least answer `/hello`.

If it can run the whole test inside the container, better!

**Comment by luxiaba** [comment]
Yes, i'm trying to do this.

**Comment by livid** [comment]
During my initial testing, it seems config override is not working as expected.

**Comment by livid** [comment]
<img width="777" alt="Screen Shot 2021-12-10 at 5 46 10 AM" src="https://user-images.githubusercontent.com/11427/145583647-18ea1a81-6e91-4503-a7f3-a48804f985a5.png">

**Comment by livid** [comment]
If it is working as we expected, `/hello` should return overridden UID instead of the one in base.py.

**Comment by luxiaba** [comment]
Yes, it's, let me check config load right now.

**Comment by luxiaba** [comment]
I think I know why it has not been updated.

I'm use flask config module to load our config, howerver flask will only load [uppercase configurations](https://flask.palletsprojects.com/en/2.0.x/config/#configuring-from-python-files), I think we should turn all configs to **uppercase**, it should be works fine.

**Comment by livid** [comment]
Understood.

UPPERCASE is also common as ENVIRONMENT VARIABLES.

So we can also override some config via env var, right?

**Comment by luxiaba** [comment]
Yes of course, but i'm not support it yet.

Do you need every config can be covered by environment variables with the same name?

**Comment by livid** [comment]
Yes, please. That would be great for Docker based deployments.

**Comment by livid** [comment]
I added some V2EX coins to your V2EX account. Now you have access to https://www.v2ex.com/i

It is also largely powered by this Remote Worker :)

Now with our recent improvements, it will support more formats with better performance and robustness.

**Comment by luxiaba** [comment]
> Yes, please. That would be great for Docker based deployments.

Sure, my first thought is that `base.py` is a complete collection of all configs, so I will only support the overwriting of these configs from env, is that ok?

**Comment by livid** [comment]
Yes, `base.py` provides the default values and a standard list of things that we can read from env var.

If we need anything new in the future, we will extend `base.py` first.

**Comment by livid** [comment]
BTW this is a little macOS SwiftUI app @kailuo and I are working on for launching backend apps in the local development environment. 😄

<img width="1012" alt="Screen Shot 2021-12-10 at 6 42 59 AM" src="https://user-images.githubusercontent.com/11427/145592093-c83dbf38-dfa9-4469-a158-d06d5901641d.png">

**Comment by luxiaba** [comment]
wow another MOD's product, seems very simple and beautiful! ☺️

**Comment by livid** [comment]
Thanks.

I tried to override REGION in staging but did not get the expected result.

Do I need any prefix or something?

<img width="777" alt="Screen Shot 2021-12-10 at 7 06 32 AM" src="https://user-images.githubusercontent.com/11427/145595600-c8dac914-5d14-4a76-9f31-5ca0a7582f41.png">

**Comment by livid** [comment]
Yeah, if we can selectively pass ENV in, then a .py override config is not required.

**Comment by luxiaba** [comment]
> I added some V2EX coins to your V2EX account. Now you have access to https://www.v2ex.com/i

Thank you for your kindness. 🥳
