### ISSUE TITLE
Test for AVIF is not working in PR #26

### ISSUE THREAD

**Issue by livid** [v2ex/remote#27]
With the current implementation, to recognize an image, it needs to be both recognized by libmagic and Pillow. And that caused test for AVIF to fail. Because while Pillow.Image can recognize it:

<img width="646" alt="Screen Shot 2021-12-14 at 7 07 43 AM" src="https://user-images.githubusercontent.com/11427/146024580-6acefcbe-8b61-4b3c-a0ad-844ef9155c84.png">

But libmagic cannot:

<img width="646" alt="Screen Shot 2021-12-14 at 7 08 15 AM" src="https://user-images.githubusercontent.com/11427/146024609-2b495a97-faa6-4477-a2cf-0e0eb9031bad.png">

If Pillow.Image can return a meaningful result, libmagic should not block the process.

**Comment by luxiaba** [comment]
> But libmagic cannot:

This line is logged by us, first i try to get mime by using magic, if magic can't get it or result is not in our supported-mime list(means we can't handle this kind of mime), i'll log this.

Actually, in the above case, `application/octet-stream` is result that mgaic get, `magic` guess mime type by the first few bytes of byte stream, same as PIL, but the types supported by PIL are limited, if PIL can recognize, `magic` should be able too.

It's a little strange. magic didn't get the correct mime from bytes content, i'll test and find out.

**Comment by luxiaba** [comment]
I test it by curl with `cap.avif` in repo, seesm normal.

![image](https://user-images.githubusercontent.com/5391976/146126222-140443a1-012f-4ec3-b11f-6c5d56534f21.png)

**Comment by livid** [comment]
I guess you are testing on macOS.

Can you try Ubuntu or Debian?

**Comment by livid** [comment]
CI is now failing for the same reason:

https://github.com/v2ex/remote/actions/runs/1578163584

**Comment by luxiaba** [comment]
Sure, let me create on first😂

**Comment by luxiaba** [comment]
Seems `magic` not support avif now, but `pillow-avif-plugin` allows PIL to handle avif.
![image](https://user-images.githubusercontent.com/5391976/146130851-bd8f6e80-dfd1-4001-88dd-68293c58653f.png)


If magic gets the valid mime then use it, otherwise try to get mime by using PIL, how about that?

**Comment by luxiaba** [comment]
Maybe there is a component in my macOS that supports magic to handle avif.🤔
![image](https://user-images.githubusercontent.com/5391976/146131608-4c621133-0957-4fa3-8373-a497ae789515.png)

**Comment by livid** [comment]
It seems Magic on macOS can recognize it. But the production server is running Debian with Docker.

Yes, we need to turn these tests green. Thanks!
