### ISSUE TITLE
Use Codecov to display test coverage automatically

### ISSUE THREAD

**Issue by luxiaba** [v2ex/remote#33]
Maybe we can use [Codecov](https://about.codecov.io/) to automatically handle the test coverage.

Use this [action](https://github.com/marketplace/actions/codecov) to integrate into CI, then we can add a bagde into readme to display test coverage automatically, should I open a PR for this?

**Comment by livid** [comment]
Currently, coverage badge is generated with this tool:

https://pypi.org/project/coverage-badge/

It is a relatively simple dependency. How about we insert it as a step in CI after pytest step?

**Comment by luxiaba** [comment]
I'd also like to keep simple and independance, `coverage-badge` is a good choice, of course we can update `coverage.svg` inside Github Action, but I'm not sure whether it's appropriate to make another commit inside Github Action, such as the code security and submitter.

Another advantage of using Codecov is we can observe change of test coverage of each PR, it will leave a message below each PR to display change of test coverage, I think this is helpful for code review. It can login directly with github account.

Actually, I think it's good too now, I'll not integrate too much external system to most of my projects, but for open source project with multi-person cooperation maybe have a try.

**Comment by luxiaba** [comment]
Looks like it's already working. 😝

**Comment by livid** [comment]
@luxiaba I created an account and merged the PR from @tssujt to make the coverage badge fully automated by Codecov.io.

Thanks for the heads up.
