### ISSUE TITLE
Flake8 does not support some syntax in Python 3.10

### ISSUE THREAD

**Issue by luxiaba** [v2ex/remote#7]
should i remove [`match`](https://github.com/v2ex/remote/blob/6edbdb1ea1d922be6a8bb3e371dde4d13e8d9361/app.py#L474-L482) syntax or ignore it in flake8, or ci will always fail :(

**Comment by livid** [comment]
Or I should remove pre-commit.ci if it caused more problems.

My local pre-commit runs fine.

You can use it locally:

```
pip install pre-commit
pre-commit
pre-commit install
```

If we have the same local pre-commit config, then pre-commit.ci is not really necessary.

**Comment by livid** [comment]
I have removed pre-commit.ci

If needed, will try GitHub action in the near future.

**Comment by luxiaba** [comment]
My local’s pre-commit works fine too, seems pre-commit.ci maybe has some problems, going be me closed😃
